import { ROLES } from "./roles";
export const ROLE_PERMISSIONS = {
  [ROLES.MANAGER]: ["VIEW_DASHBOARD","VIEW_REPORTS","CREATE_CUSTOMER","UPDATE_CUSTOMER","DELETE_CUSTOMER","VIEW_CUSTOMER","CREATE_SITE","UPDATE_SITE","DELETE_SITE","VIEW_SITE","CREATE_WO","UPDATE_WO","DELETE_WO","VIEW_WO","ASSIGN_WO","CANCEL_WO","CLOSE_WO","ADD_PARTS","UPDATE_PARTS","VIEW_PARTS","DELETE_PART","VIEW_LOG_TIME","REVIEW_REQUEST","CONVERT_REQUEST","CLOSE_REQUEST","CANCEL_REQUEST"],
  [ROLES.DISPATCHER]: ["VIEW_DASHBOARD","CREATE_CUSTOMER","UPDATE_CUSTOMER","VIEW_CUSTOMER","CREATE_SITE","UPDATE_SITE","VIEW_SITE","CREATE_WO","UPDATE_WO","VIEW_WO","ASSIGN_WO","CANCEL_WO","CLOSE_WO","REVIEW_REQUEST","CONVERT_REQUEST","CLOSE_REQUEST","CANCEL_REQUEST"],
  [ROLES.TECHNICIAN]: ["VIEW_WO","START_WORK","HOLD_WORK","RESUME_WORK","COMPLETED_WORK","USE_PARTS","VIEW_PARTS","ADD_LOG_TIME","VIEW_LOG_TIME"],
  [ROLES.CUSTOMER]: ["RAISE_REQUEST","VIEW_OWN_REQUEST"],
};
export const can = (role, permission) => ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
